// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Passenger.Contract.Context;

namespace Passenger.Contract.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200821115357_initialmigrationDbCreation")]
    partial class initialmigrationDbCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Passenger.Entities.Models.CityDetails", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityName")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictID")
                        .HasColumnType("int");

                    b.HasKey("CityID");

                    b.ToTable("City_Details");
                });

            modelBuilder.Entity("Passenger.Entities.Models.CountryDetails", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Country_Details");
                });

            modelBuilder.Entity("Passenger.Entities.Models.DistrictDetails", b =>
                {
                    b.Property<int>("DistrictID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateID")
                        .HasColumnType("int");

                    b.HasKey("DistrictID");

                    b.ToTable("District_Details");
                });

            modelBuilder.Entity("Passenger.Entities.Models.DriverRegistration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DriverID")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDTTM")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictID")
                        .HasColumnType("int");

                    b.Property<int?>("DriverAge")
                        .HasColumnType("int");

                    b.Property<long>("DriverContact")
                        .HasColumnType("bigint");

                    b.Property<string>("DriverEmail")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("PinCode")
                        .HasColumnType("int");

                    b.Property<int>("StateID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDTTM")
                        .HasColumnType("datetime2");

                    b.HasKey("ID", "DriverID");

                    b.ToTable("Driver_Registrations");
                });

            modelBuilder.Entity("Passenger.Entities.Models.PassengerRegistration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PassengerID")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedDTTM")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictID")
                        .HasColumnType("int");

                    b.Property<int?>("PassengerAge")
                        .HasColumnType("int");

                    b.Property<long>("PassengerContact")
                        .HasColumnType("bigint");

                    b.Property<string>("PassengerEmail")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<int>("StateID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDTTM")
                        .HasColumnType("datetime2");

                    b.HasKey("ID", "PassengerID");

                    b.ToTable("Passenger_Registrations");
                });

            modelBuilder.Entity("Passenger.Entities.Models.StateDetails", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateID");

                    b.ToTable("State_Details");
                });

            modelBuilder.Entity("Passenger.Entities.Models.VehicleDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsuranceEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsuranceStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVehicleUnderInsurance")
                        .HasColumnType("bit");

                    b.Property<int?>("SeatsInVehicle")
                        .HasColumnType("int");

                    b.Property<int>("VehicleNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Vehicle_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
